#
# Makefile for the Synaptics DSX touchscreen driver.
#

obj-$(CONFIG_TOUCHSCREEN_TD4310_LANSI_E7) += synaptics_dsx_i2c.o
obj-$(CONFIG_TOUCHSCREEN_TD4310_LANSI_E7) += synaptics_dsx_core.o
obj-$(CONFIG_TOUCHSCREEN_TD4310_LANSI_E7) += synaptics_dsx_rmi_dev.o
obj-$(CONFIG_TOUCHSCREEN_TD4310_LANSI_E7) += synaptics_dsx_fw_update.o
obj-$(CONFIG_TOUCHSCREEN_TD4310_LANSI_E7) += synaptics_dsx_test_reporting.o
